kind: pipeline
name: default

steps:
  - name: app-compile
    image: bluerain/elixir:1.12-slim
    environment:
      MIX_ENV: prod
    commands:
      - mix deps.get
      - mix compile

  - name: assets-build
    image: node:buster
    commands:
      - npm install --prefix assets
      - npm run deploy --prefix assets

  - name: app-build
    image: bluerain/elixir:1.12-slim
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - mix phx.digest
      - mix release

  - name: image-push
    image: plugins/docker
    settings:
      repo: bluerain/policr-mini
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push
