---
kind: pipeline
type: docker
name: default

steps:
  - name: app-compile
    image: elixir:1.13.4-slim
    environment:
      MIX_ENV: prod
    commands:
      - apt update && apt install git -y
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix compile

  - name: assets-build
    image: node:lts-buster
    commands:
      - npm install --prefix assets
      - npm run deploy --prefix assets

  - name: app-build
    image: elixir:1.13.4-slim
    pull: always
    environment:
      MIX_ENV: prod
    commands:
      - apt update && apt install git -y
      - mix local.hex --force
      - mix local.rebar --force
      - mix phx.digest
      - mix release

  - name: image-push
    image: plugins/docker
    settings:
      repo: telestd/policr-mini
      username: telestd
      password:
        from_secret: hub_pass_telestd
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push

  - name: image-push-obsolete
    image: plugins/docker
    settings:
      repo: bluerain/policr-mini
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push
